import { StyledSystemProps, useTheme } from '@paisidevs/tra-theme';
import React, { FC } from 'react';
import { Box } from '../Box';

export interface IChatProps extends StyledSystemProps {}

/**
 * @render react
 * @name Chart component
 * @description Defines a clickable button.
 * @example
 * <Chart />
 */

export const Chart: FC<IChatProps> = () => {
  const { theme } = useTheme();

  return (
    <Box>
      <div
        aria-label="A chart."
        style={{
          left: '0px',
          top: '0px',
          width: '100%',
          height: '100%',
        }}
      >
        <svg
          width="1276"
          height="300"
          aria-label="A chart."
          style={{ overflow: 'hidden' }}
        >
          <defs id="_ABSTRACT_RENDERER_ID_0">
            <clipPath id="_ABSTRACT_RENDERER_ID_1">
              <rect x="80" y="20" width="1186" height="185" />
            </clipPath>
          </defs>
          <rect
            x="0"
            y="0"
            width="1276"
            height="300"
            stroke="none"
            strokeWidth="0"
            fill="none"
          />
          <g>
            <rect
              x="80"
              y="20"
              width="1186"
              height="185"
              stroke="none"
              strokeWidth="0"
              fillOpacity="0"
              fill="none"
            />
            <g clipPath="url(https://www.premierleague.com/tables#_ABSTRACT_RENDERER_ID_1)">
              <g>
                <rect
                  x="80"
                  y="20"
                  width="1186"
                  height="1"
                  stroke="none"
                  strokeWidth="0"
                  fill={theme.colors.border.default}
                />
                <rect
                  x="80"
                  y="59"
                  width="1186"
                  height="1"
                  stroke="none"
                  strokeWidth="0"
                  fill={theme.colors.border.default}
                />
                <rect
                  x="80"
                  y="107"
                  width="1186"
                  height="1"
                  stroke="none"
                  strokeWidth="0"
                  fill={theme.colors.border.default}
                />
                <rect
                  x="80"
                  y="156"
                  width="1186"
                  height="1"
                  stroke="none"
                  strokeWidth="0"
                  fill={theme.colors.border.default}
                />
                <rect
                  x="80"
                  y="204"
                  width="1186"
                  height="1"
                  stroke="none"
                  strokeWidth="0"
                  fill={theme.colors.border.default}
                />
              </g>
              <g>
                <g>
                  <path
                    d="M80.5,10.81578947368421L80.5,10.81578947368421L80.5,39.86842105263158L124.38888888888889,20.5L168.27777777777777,20.5L212.16666666666666,20.5L256.05555555555554,20.5L299.94444444444446,20.5L343.8333333333333,20.5L387.7222222222222,20.5L431.6111111111111,20.5L475.5,20.5L519.3888888888889,20.5L563.2777777777777,20.5L607.1666666666666,20.5L651.0555555555555,20.5L694.9444444444443,20.5L738.8333333333333,20.5L782.7222222222222,20.5L826.6111111111111,20.5L870.5,20.5L914.3888888888888,20.5L958.2777777777777,20.5L1002.1666666666666,20.5L1046.0555555555554,20.5L1089.9444444444443,20.5L1133.8333333333333,20.5L1177.7222222222222,20.5L1221.611111111111,20.5L1265.5,20.5L1265.5,10.81578947368421L1265.5,10.81578947368421Z"
                    stroke="none"
                    strokeWidth="0"
                    fillOpacity="0.3"
                    fill="none"
                  />
                </g>
              </g>
              <g>
                <path
                  d="M80.5,39.86842105263158L124.38888888888889,20.5L168.27777777777777,20.5L212.16666666666666,20.5L256.05555555555554,20.5L299.94444444444446,20.5L343.8333333333333,20.5L387.7222222222222,20.5L431.6111111111111,20.5L475.5,20.5L519.3888888888889,20.5L563.2777777777777,20.5L607.1666666666666,20.5L651.0555555555555,20.5L694.9444444444443,20.5L738.8333333333333,20.5L782.7222222222222,20.5L826.6111111111111,20.5L870.5,20.5L914.3888888888888,20.5L958.2777777777777,20.5L1002.1666666666666,20.5L1046.0555555555554,20.5L1089.9444444444443,20.5L1133.8333333333333,20.5L1177.7222222222222,20.5L1221.611111111111,20.5L1265.5,20.5"
                  stroke={theme.colors.gray[500]}
                  strokeWidth="2"
                  fillOpacity="1"
                  fill="none"
                />
              </g>
            </g>
            <g>
              <circle
                cx="80.5"
                cy="39.86842105263158"
                r="6"
                stroke={theme.colors.background.surface}
                strokeWidth="2"
                fill="#13cf00"
              />
              <circle
                cx="124.38888888888889"
                cy="20.5"
                r="6"
                stroke={theme.colors.background.surface}
                strokeWidth="2"
                fill="#13cf00"
              />
              <circle
                cx="168.27777777777777"
                cy="20.5"
                r="6"
                stroke={theme.colors.background.surface}
                strokeWidth="2"
                fill="#13cf00"
              />
              <circle
                cx="212.16666666666666"
                cy="20.5"
                r="6"
                stroke={theme.colors.background.surface}
                strokeWidth="2"
                fill="#13cf00"
              />
              <circle
                cx="256.05555555555554"
                cy="20.5"
                r="6"
                stroke={theme.colors.background.surface}
                strokeWidth="2"
                fill="#13cf00"
              />
              <circle
                cx="299.94444444444446"
                cy="20.5"
                r="6"
                stroke={theme.colors.background.surface}
                strokeWidth="2"
                fill="#13cf00"
              />
              <circle
                cx="343.8333333333333"
                cy="20.5"
                r="6"
                stroke={theme.colors.background.surface}
                strokeWidth="2"
                fill="#13cf00"
              />
              <circle
                cx="387.7222222222222"
                cy="20.5"
                r="6"
                stroke={theme.colors.background.surface}
                strokeWidth="2"
                fill="#13cf00"
              />
              <circle
                cx="431.6111111111111"
                cy="20.5"
                r="6"
                stroke={theme.colors.background.surface}
                strokeWidth="2"
                fill="#76766f"
              />
              <circle
                cx="475.5"
                cy="20.5"
                r="6"
                stroke={theme.colors.background.surface}
                strokeWidth="2"
                fill="#13cf00"
              />
              <circle
                cx="519.3888888888889"
                cy="20.5"
                r="6"
                stroke={theme.colors.background.surface}
                strokeWidth="2"
                fill="#13cf00"
              />
              <circle
                cx="563.2777777777777"
                cy="20.5"
                r="6"
                stroke={theme.colors.background.surface}
                strokeWidth="2"
                fill="#13cf00"
              />
              <circle
                cx="607.1666666666666"
                cy="20.5"
                r="6"
                stroke={theme.colors.background.surface}
                strokeWidth="2"
                fill="#13cf00"
              />
              <circle
                cx="651.0555555555555"
                cy="20.5"
                r="6"
                stroke={theme.colors.background.surface}
                strokeWidth="2"
                fill="#13cf00"
              />
              <circle
                cx="694.9444444444443"
                cy="20.5"
                r="6"
                stroke={theme.colors.background.surface}
                strokeWidth="2"
                fill="#13cf00"
              />
              <circle
                cx="738.8333333333333"
                cy="20.5"
                r="6"
                stroke={theme.colors.background.surface}
                strokeWidth="2"
                fill="#13cf00"
              />
              <circle
                cx="782.7222222222222"
                cy="20.5"
                r="6"
                stroke={theme.colors.background.surface}
                strokeWidth="2"
                fill="#13cf00"
              />
              <circle
                cx="826.6111111111111"
                cy="20.5"
                r="6"
                stroke={theme.colors.background.surface}
                strokeWidth="2"
                fill="#13cf00"
              />
              <circle
                cx="870.5"
                cy="20.5"
                r="6"
                stroke={theme.colors.background.surface}
                strokeWidth="2"
                fill="#13cf00"
              />
              <circle
                cx="914.3888888888888"
                cy="20.5"
                r="6"
                stroke={theme.colors.background.surface}
                strokeWidth="2"
                fill="#13cf00"
              />
              <circle
                cx="958.2777777777777"
                cy="20.5"
                r="6"
                stroke={theme.colors.background.surface}
                strokeWidth="2"
                fill="#13cf00"
              />
              <circle
                cx="1002.1666666666666"
                cy="20.5"
                r="6"
                stroke={theme.colors.background.surface}
                strokeWidth="2"
                fill="#13cf00"
              />
              <circle
                cx="1046.0555555555554"
                cy="20.5"
                r="6"
                stroke={theme.colors.background.surface}
                strokeWidth="2"
                fill="#13cf00"
              />
              <circle
                cx="1089.9444444444443"
                cy="20.5"
                r="6"
                stroke={theme.colors.background.surface}
                strokeWidth="2"
                fill="#13cf00"
              />
              <circle
                cx="1133.8333333333333"
                cy="20.5"
                r="6"
                stroke={theme.colors.background.surface}
                strokeWidth="2"
                fill="#13cf00"
              />
              <circle
                cx="1177.7222222222222"
                cy="20.5"
                r="6"
                stroke={theme.colors.background.surface}
                strokeWidth="2"
                fill="#13cf00"
              />
              <circle
                cx="1221.611111111111"
                cy="20.5"
                r="6"
                stroke={theme.colors.background.surface}
                strokeWidth="2"
                fill="#d81920"
              />
              <circle
                cx="1265.5"
                cy="20.5"
                r="6"
                stroke={theme.colors.background.surface}
                strokeWidth="2"
                fill="#13cf00"
              />
            </g>
            <g>
              <g>
                <text
                  textAnchor="middle"
                  x="80.5"
                  y="222.2"
                  fontFamily="Roboto"
                  fontSize="12"
                  stroke="none"
                  strokeWidth="0"
                  fill={theme.colors.text.default}
                >
                  1
                </text>
              </g>
              <g>
                <text
                  textAnchor="middle"
                  x="124.38888888888889"
                  y="222.2"
                  fontFamily="Roboto"
                  fontSize="12"
                  stroke="none"
                  strokeWidth="0"
                  fill={theme.colors.text.default}
                >
                  2
                </text>
              </g>
              <g>
                <text
                  textAnchor="middle"
                  x="168.27777777777777"
                  y="222.2"
                  fontFamily="Roboto"
                  fontSize="12"
                  stroke="none"
                  strokeWidth="0"
                  fill={theme.colors.text.default}
                >
                  3
                </text>
              </g>
              <g>
                <text
                  textAnchor="middle"
                  x="212.16666666666666"
                  y="222.2"
                  fontFamily="Roboto"
                  fontSize="12"
                  stroke="none"
                  strokeWidth="0"
                  fill={theme.colors.text.default}
                >
                  4
                </text>
              </g>
              <g>
                <text
                  textAnchor="middle"
                  x="256.05555555555554"
                  y="222.2"
                  fontFamily="Roboto"
                  fontSize="12"
                  stroke="none"
                  strokeWidth="0"
                  fill={theme.colors.text.default}
                >
                  5
                </text>
              </g>
              <g>
                <text
                  textAnchor="middle"
                  x="299.94444444444446"
                  y="222.2"
                  fontFamily="Roboto"
                  fontSize="12"
                  stroke="none"
                  strokeWidth="0"
                  fill={theme.colors.text.default}
                >
                  6
                </text>
              </g>
              <g>
                <text
                  textAnchor="middle"
                  x="343.8333333333333"
                  y="222.2"
                  fontFamily="Roboto"
                  fontSize="12"
                  stroke="none"
                  strokeWidth="0"
                  fill={theme.colors.text.default}
                >
                  7
                </text>
              </g>
              <g>
                <text
                  textAnchor="middle"
                  x="387.7222222222222"
                  y="222.2"
                  fontFamily="Roboto"
                  fontSize="12"
                  stroke="none"
                  strokeWidth="0"
                  fill={theme.colors.text.default}
                >
                  8
                </text>
              </g>
              <g>
                <text
                  textAnchor="middle"
                  x="431.6111111111111"
                  y="222.2"
                  fontFamily="Roboto"
                  fontSize="12"
                  stroke="none"
                  strokeWidth="0"
                  fill={theme.colors.text.default}
                >
                  9
                </text>
              </g>
              <g>
                <text
                  textAnchor="middle"
                  x="475.5"
                  y="222.2"
                  fontFamily="Roboto"
                  fontSize="12"
                  stroke="none"
                  strokeWidth="0"
                  fill={theme.colors.text.default}
                >
                  10
                </text>
              </g>
              <g>
                <text
                  textAnchor="middle"
                  x="519.3888888888889"
                  y="222.2"
                  fontFamily="Roboto"
                  fontSize="12"
                  stroke="none"
                  strokeWidth="0"
                  fill={theme.colors.text.default}
                >
                  11
                </text>
              </g>
              <g>
                <text
                  textAnchor="middle"
                  x="563.2777777777777"
                  y="222.2"
                  fontFamily="Roboto"
                  fontSize="12"
                  stroke="none"
                  strokeWidth="0"
                  fill={theme.colors.text.default}
                >
                  12
                </text>
              </g>
              <g>
                <text
                  textAnchor="middle"
                  x="607.1666666666666"
                  y="222.2"
                  fontFamily="Roboto"
                  fontSize="12"
                  stroke="none"
                  strokeWidth="0"
                  fill={theme.colors.text.default}
                >
                  13
                </text>
              </g>
              <g>
                <text
                  textAnchor="middle"
                  x="651.0555555555555"
                  y="222.2"
                  fontFamily="Roboto"
                  fontSize="12"
                  stroke="none"
                  strokeWidth="0"
                  fill={theme.colors.text.default}
                >
                  14
                </text>
              </g>
              <g>
                <text
                  textAnchor="middle"
                  x="694.9444444444443"
                  y="222.2"
                  fontFamily="Roboto"
                  fontSize="12"
                  stroke="none"
                  strokeWidth="0"
                  fill={theme.colors.text.default}
                >
                  15
                </text>
              </g>
              <g>
                <text
                  textAnchor="middle"
                  x="738.8333333333333"
                  y="222.2"
                  fontFamily="Roboto"
                  fontSize="12"
                  stroke="none"
                  strokeWidth="0"
                  fill={theme.colors.text.default}
                >
                  16
                </text>
              </g>
              <g>
                <text
                  textAnchor="middle"
                  x="782.7222222222222"
                  y="222.2"
                  fontFamily="Roboto"
                  fontSize="12"
                  stroke="none"
                  strokeWidth="0"
                  fill={theme.colors.text.default}
                >
                  17
                </text>
              </g>
              <g>
                <text
                  textAnchor="middle"
                  x="826.6111111111111"
                  y="222.2"
                  fontFamily="Roboto"
                  fontSize="12"
                  stroke="none"
                  strokeWidth="0"
                  fill={theme.colors.text.default}
                >
                  18
                </text>
              </g>
              <g>
                <text
                  textAnchor="middle"
                  x="870.5"
                  y="222.2"
                  fontFamily="Roboto"
                  fontSize="12"
                  stroke="none"
                  strokeWidth="0"
                  fill={theme.colors.text.default}
                >
                  19
                </text>
              </g>
              <g>
                <text
                  textAnchor="middle"
                  x="914.3888888888888"
                  y="222.2"
                  fontFamily="Roboto"
                  fontSize="12"
                  stroke="none"
                  strokeWidth="0"
                  fill={theme.colors.text.default}
                >
                  20
                </text>
              </g>
              <g>
                <text
                  textAnchor="middle"
                  x="958.2777777777777"
                  y="222.2"
                  fontFamily="Roboto"
                  fontSize="12"
                  stroke="none"
                  strokeWidth="0"
                  fill={theme.colors.text.default}
                >
                  21
                </text>
              </g>
              <g>
                <text
                  textAnchor="middle"
                  x="1002.1666666666666"
                  y="222.2"
                  fontFamily="Roboto"
                  fontSize="12"
                  stroke="none"
                  strokeWidth="0"
                  fill={theme.colors.text.default}
                >
                  22
                </text>
              </g>
              <g>
                <text
                  textAnchor="middle"
                  x="1046.0555555555554"
                  y="222.2"
                  fontFamily="Roboto"
                  fontSize="12"
                  stroke="none"
                  strokeWidth="0"
                  fill={theme.colors.text.default}
                >
                  24
                </text>
              </g>
              <g>
                <text
                  textAnchor="middle"
                  x="1089.9444444444443"
                  y="222.2"
                  fontFamily="Roboto"
                  fontSize="12"
                  stroke="none"
                  strokeWidth="0"
                  fill={theme.colors.text.default}
                >
                  25
                </text>
              </g>
              <g>
                <text
                  textAnchor="middle"
                  x="1133.8333333333333"
                  y="222.2"
                  fontFamily="Roboto"
                  fontSize="12"
                  stroke="none"
                  strokeWidth="0"
                  fill={theme.colors.text.default}
                >
                  26
                </text>
              </g>
              <g>
                <text
                  textAnchor="middle"
                  x="1177.7222222222222"
                  y="222.2"
                  fontFamily="Roboto"
                  fontSize="12"
                  stroke="none"
                  strokeWidth="0"
                  fill={theme.colors.text.default}
                >
                  27
                </text>
              </g>
              <g>
                <text
                  textAnchor="middle"
                  x="1221.611111111111"
                  y="222.2"
                  fontFamily="Roboto"
                  fontSize="12"
                  stroke="none"
                  strokeWidth="0"
                  fill={theme.colors.text.default}
                >
                  28
                </text>
              </g>
              <g>
                <text
                  textAnchor="middle"
                  x="1265.5"
                  y="222.2"
                  fontFamily="Roboto"
                  fontSize="12"
                  stroke="none"
                  strokeWidth="0"
                  fill={theme.colors.text.default}
                >
                  29
                </text>
              </g>
              <g>
                <text
                  textAnchor="end"
                  x="68"
                  y="24.7"
                  fontFamily="Roboto"
                  fontSize="12"
                  stroke="none"
                  strokeWidth="0"
                  fill={theme.colors.text.default}
                >
                  1
                </text>
              </g>
              <g>
                <text
                  textAnchor="end"
                  x="68"
                  y="63.43684210526316"
                  fontFamily="Roboto"
                  fontSize="12"
                  stroke="none"
                  strokeWidth="0"
                  fill={theme.colors.text.default}
                >
                  5
                </text>
              </g>
              <g>
                <text
                  textAnchor="end"
                  x="68"
                  y="111.8578947368421"
                  fontFamily="Roboto"
                  fontSize="12"
                  stroke="none"
                  strokeWidth="0"
                  fill={theme.colors.text.default}
                >
                  10
                </text>
              </g>
              <g>
                <text
                  textAnchor="end"
                  x="68"
                  y="160.27894736842106"
                  fontFamily="Roboto"
                  fontSize="12"
                  stroke="none"
                  strokeWidth="0"
                  fill={theme.colors.text.default}
                >
                  15
                </text>
              </g>
              <g>
                <text
                  textAnchor="end"
                  x="68"
                  y="208.7"
                  fontFamily="Roboto"
                  fontSize="12"
                  stroke="none"
                  strokeWidth="0"
                  fill={theme.colors.text.default}
                >
                  20
                </text>
              </g>
            </g>
          </g>
          <g>
            <g>
              <text
                textAnchor="middle"
                x="673"
                y="266.2"
                fontFamily="Roboto"
                fontSize="12"
                stroke="none"
                strokeWidth="0"
                fill={theme.colors.text.default}
              >
                Matches Played
              </text>
              <rect
                x="80"
                y="256"
                width="1186"
                height="12"
                stroke="none"
                strokeWidth="0"
                fillOpacity="0"
                fill="#ffffff"
              />
            </g>
            <g>
              <text
                textAnchor="middle"
                x="31.7"
                y="112.5"
                fontFamily="Roboto"
                fontSize="12"
                transform="rotate(-90 31.7 112.5)"
                stroke="none"
                strokeWidth="0"
                fill={theme.colors.text.default}
              >
                Position
              </text>
              <path
                d="M21.499999999999993,205L21.500000000000007,20L33.50000000000001,20.000000000000004L33.49999999999999,205Z"
                stroke="none"
                strokeWidth="0"
                fillOpacity="0"
                fill="#ffffff"
              />
            </g>
          </g>
        </svg>
        <div
          aria-label="A tabular representation of the data in the chart."
          style={{
            position: 'absolute',
            left: '-10000px',
            top: 'auto',
            width: '1px',
            height: '1px',
            overflow: 'hidden',
          }}
        >
          <table>
            <thead>
              <tr>
                <th>Year</th>
                <th>LIV</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>1</td>
                <td>3</td>
              </tr>
              <tr>
                <td>2</td>
                <td>1</td>
              </tr>
              <tr>
                <td>3</td>
                <td>1</td>
              </tr>
              <tr>
                <td>4</td>
                <td>1</td>
              </tr>
              <tr>
                <td>5</td>
                <td>1</td>
              </tr>
              <tr>
                <td>6</td>
                <td>1</td>
              </tr>
              <tr>
                <td>7</td>
                <td>1</td>
              </tr>
              <tr>
                <td>8</td>
                <td>1</td>
              </tr>
              <tr>
                <td>9</td>
                <td>1</td>
              </tr>
              <tr>
                <td>10</td>
                <td>1</td>
              </tr>
              <tr>
                <td>11</td>
                <td>1</td>
              </tr>
              <tr>
                <td>12</td>
                <td>1</td>
              </tr>
              <tr>
                <td>13</td>
                <td>1</td>
              </tr>
              <tr>
                <td>14</td>
                <td>1</td>
              </tr>
              <tr>
                <td>15</td>
                <td>1</td>
              </tr>
              <tr>
                <td>16</td>
                <td>1</td>
              </tr>
              <tr>
                <td>17</td>
                <td>1</td>
              </tr>
              <tr>
                <td>18</td>
                <td>1</td>
              </tr>
              <tr>
                <td>19</td>
                <td>1</td>
              </tr>
              <tr>
                <td>20</td>
                <td>1</td>
              </tr>
              <tr>
                <td>21</td>
                <td>1</td>
              </tr>
              <tr>
                <td>22</td>
                <td>1</td>
              </tr>
              <tr>
                <td>24</td>
                <td>1</td>
              </tr>
              <tr>
                <td>25</td>
                <td>1</td>
              </tr>
              <tr>
                <td>26</td>
                <td>1</td>
              </tr>
              <tr>
                <td>27</td>
                <td>1</td>
              </tr>
              <tr>
                <td>28</td>
                <td>1</td>
              </tr>
              <tr>
                <td>29</td>
                <td>1</td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </Box>
  );
};
